project:
  type: website
  output-dir: docs

website:
  title: "Sumin Kim"
  site-url: https://mudfishey.github.io/suminkim/
  description: "Pharmacist & Epidemiologist"
  favicon: favicon.ico
  
  navbar:
    background: primary
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/mudfishey
      - icon: linkedin
        href: https://www.linkedin.com/in/sumin-kim-07788093/
        
    
  page-footer:
    left: "© 2026 Sumin Kim"
    right: 
      - icon: envelope
        href: mailto:kim_smin@outlook.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    smooth-scroll: true
    
editor: visual
